/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import { core } from "@nexus/schema"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    date<FieldName extends string>(fieldName: FieldName, opts?: core.ScalarInputFieldConfig<core.GetGen3<"inputTypes", TypeName, FieldName>>): void // "Date";
    datetime<FieldName extends string>(fieldName: FieldName, opts?: core.ScalarInputFieldConfig<core.GetGen3<"inputTypes", TypeName, FieldName>>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Date";
    datetime<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  Date: any
  DateTime: any
}

export interface NexusGenRootTypes {
  Leaderboard: { // root type
    country: string; // String!
    leaderboard_id: number; // Int!
    name: string; // String!
    profile_id: number; // Int!
    rating: number; // Int!
  }
  Match: { // root type
    leaderboard_id: number; // Int!
    match_id: string; // String!
    name: string; // String!
  }
  Mutation: {};
  Player: { // root type
    match_id: string; // String!
    name: string; // String!
    profile_id: number; // Int!
    rating?: number | null; // Int
  }
  Profile: { // root type
    name: string; // String!
    profile_id: number; // Int!
  }
  Query: {};
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  String: NexusGenScalars['String'];
  Int: NexusGenScalars['Int'];
  Float: NexusGenScalars['Float'];
  Boolean: NexusGenScalars['Boolean'];
  ID: NexusGenScalars['ID'];
  Date: NexusGenScalars['Date'];
  DateTime: NexusGenScalars['DateTime'];
}

export interface NexusGenFieldTypes {
  Leaderboard: { // field return type
    country: string; // String!
    leaderboard_id: number; // Int!
    name: string; // String!
    profile_id: number; // Int!
    rating: number; // Int!
  }
  Match: { // field return type
    finished: NexusGenScalars['DateTime'] | null; // DateTime
    leaderboard_id: number; // Int!
    match_id: string; // String!
    name: string; // String!
    players: NexusGenRootTypes['Player'][]; // [Player!]!
    started: NexusGenScalars['DateTime']; // DateTime!
  }
  Mutation: { // field return type
    publish: number | null; // Int
  }
  Player: { // field return type
    match: NexusGenRootTypes['Match']; // Match!
    match_id: string; // String!
    name: string; // String!
    profile_id: number; // Int!
    rating: number | null; // Int
  }
  Profile: { // field return type
    leaderboard1v1: NexusGenRootTypes['Leaderboard'] | null; // Leaderboard
    name: string; // String!
    profile_id: number; // Int!
  }
  Query: { // field return type
    match: NexusGenRootTypes['Match']; // Match!
    matches: NexusGenRootTypes['Match'][]; // [Match!]!
    profile: NexusGenRootTypes['Profile']; // Profile!
    temp: NexusGenRootTypes['Match'][]; // [Match!]!
    temp2: NexusGenRootTypes['Match'][]; // [Match!]!
  }
}

export interface NexusGenArgTypes {
  Query: {
    match: { // args
      matchId: string; // String!
    }
    matches: { // args
      count: number; // Int!
      leaderboard_id?: number | null; // Int
      profile_id?: number | null; // Int
      start: number; // Int!
    }
    profile: { // args
      profile_id?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = "Leaderboard" | "Match" | "Mutation" | "Player" | "Profile" | "Query";

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = "Boolean" | "Date" | "DateTime" | "Float" | "ID" | "Int" | "String";

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
}