language: java

env:
  global:
    - NODE_VERSION="12.13.1"
    - YARN_VERSION="1.21.1"

services:
  - docker

jobs:
  include:

    - stage: publish
#      if: tag =~ ^match-v.+$
      env:
        - CACHE_NAME=match
        - IMAGE_NAME=denniske/aoe2companion-graphql
#      before_install:
#        - nvm install $NODE_VERSION
#        - nvm use $NODE_VERSION
#        - sudo apt-get update
#        - sudo apt-get -y install gettext-base
#        - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
#        - chmod u+x ./kubectl
#        - sudo mv kubectl /usr/local/bin/
      script:
        - echo $ID_CI_RSA_BASE64 > id_ci_rsa.base64
        - base64 --decode id_ci_rsa.base64 > ~/.ssh/id_rsa
        - echo $KNOWN_HOSTS_BASE64 > known_hosts.base64
        - base64 --decode known_hosts.base64 > ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
        - chmod 600 ~/.ssh/id_rsa

        - docker build -t $IMAGE_NAME:$TRAVIS_COMMIT .
        - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        - docker push $IMAGE_NAME:$TRAVIS_COMMIT

        - bash ./deploy.sh
        - scp docker-compose.yml root@116.203.245.222:/root
        - ssh root@116.203.245.222 docker-compose up -d
